### ISSUE TITLE
Add dev documentation

### ISSUE THREAD

**Issue by T3kstiil3** [Zenika/Zenika-Resume#29]
Add documentation 📑📑for 
- Use postgres:
```
PGUSER=postgres \
  PGHOST=localhost \
  PGPASSWORD=changeme \
  PGDATABASE=resume \
  PGPORT=5432 \
  node server.js
```

- start a postgres contenair and pgadmin...
docker-compose.yml
```
version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - /tmp/data/postgres:/data/postgres
       - ./database.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
       - /tmp/data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
```
